version: "3.9"

services:
  db:
    image:mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: letmein2
      MYSQL_DATABASE: developmentdb
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  platform:
    image: theharbormaster/struts-demo:latest
    ports:
      - "8080:8080"
    environment:
        DATABASE_URL: jdbc:mysql://db:3306/developmentdb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
        DATABASE_PASSWORD: letmein2
    depends_on:
      - db
    links:
      - db

